### ISSUE TITLE
Deploying with debian + Helm, and issue importing loaded modules after creating notebooks

### ISSUE THREAD

**Issue by vemonet** [guimou/odh-highlander#1]
Thanks a lot @guimou for this nice implementation of Lmod and EasyBuild!

I gave it a try on our OKD4.6 cluster, and it works well

I deployed it outside of Open Data Hub, I reused your EasyBuild image (next step will be to publish a custom one), but I reimplemented the Lmod installation in a `jupyter/scipy-notebook` from the popular [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks) (which is based on debian). Then we deployed the JupyterLab image connected to the EasyBuild volume using a generic Helm chart to deploy JupyterLab notebook on Kubernetes/OpenShift

Small remark: it would be interesting to have a direct link to the `Dockerfile`/commands to install lmod in JupyterLab, I could not find the `Dockerfile` you used for the s2i-lmod image, but I could find some [manifests on quay.io](https://quay.io/repository/guimou/s2i-generic-datascience-lmod-notebook/manifest/sha256:4329da31f6ef918b1f3878b037c7517cb72511bf1fcbb632b50dcd5cd0802715) that were already helpful

> Edit: found the image here finally: https://github.com/guimou/s2i-lmod-notebook

You can find the complete instructions and files to build JupyterLab lmod based on debian, and deploy it with a Helm chart, here: https://github.com/MaastrichtU-IDS/jupyterlab/tree/main/lmod

Also I noticed that we need to create notebooks after loading a new module. If we create a notebook before loading a module, the module is not found when we `import`, and it stays this way even if we load the module and close/reopen the notebook (we tested it with `tensorflow`). 

Any idea how we can make sure the loaded modules are properly taken into account by all notebooks?

**Comment by guimou** [comment]
Closing to make some cleanup before going to the next phase with ODH-Highlander.
